language: python
python:
  - "2.7"
deploy:
  provider: openshift
  user: iblancasa@gmail.com
  password:
    secure: QH+5fB99tRLP4mC6zllJdbbvFvtu22iG1yomuZ+WGplN3pBsVRYPGXRat3xFhsRB5h7BzEs8YS4t0R2FTyt5Elh5/xY7KM2qIqK8iPQ07iavgcxyEORxyUh3SVLskIsrat4a66MoW4CDDY8elggmGA+Wmv2Hl0R+wXTz2c/It2w=
  app: prometheusinwatch
  domain: iblancasa
  on:
    repo: Prometheus-inWatch/server-inwatch
