#!/usr/bin/python
# -*- coding: utf-8 -*-
import os

virtenv = os.environ['APPDIR'] + '/virtenv/'
os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python2.6/site-packages')
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
try:
    execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
    pass

import web
from web.contrib.template import render_mako

urls = (
        '/', 'index'
        )
render = render_mako(
        directories=[os.environ['OPENSHIFT_REPO_DIR']+'/wsgi/templates'],
        input_encoding='utf-8',
        output_encoding='utf-8',
        )



class index:
    def GET(self):
        web.header('Content-Type','text/html; charset=utf-8', unique=True) 
        return render.index()

application = web.application(urls, globals()).wsgifunc()

#
# Below for testing only
#
if __name__ == '__main__':
	from wsgiref.simple_server import make_server
	httpd = make_server('localhost', 8051, application)
	# Wait for a single request, serve it and quit.
	httpd.handle_request()
